-- Table: public.useraccount

-- DROP TABLE IF EXISTS public.useraccount;

CREATE TABLE IF NOT EXISTS public.useraccount
(
    userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
    auth0_id character varying(255) COLLATE pg_catalog."default",
    userscore integer,
    user_credit integer DEFAULT 770,
    user_name character varying(255) COLLATE pg_catalog."default",
    has_submitted boolean DEFAULT false,
    time_submitted bigint
);

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.useraccount
    OWNER to admin;